name: version
description: Provides a simple class for parsing and comparing semantic versions as defined by http://semver.org/
version: 3.0.2
homepage: https://github.com/dartninja/version

environment:
  sdk: '>=2.12.0 <3.0.0'
dev_dependencies:
  test: ^1.16.3
