name: version
description: Provides a simple class for parsing and comparing semantic versions as defined by http://semver.org/
version: 1.0.3
homepage: https://github.com/dartninja/version
author: Matthew Barbour <sanmadjack@gmail.com>

environment:
  sdk: '>=1.12.0 <3.0.0'
dev_dependencies:
  test: any